version: '3'

services:
  client:
    build:
      context: ../client
      dockerfile: ../docker/client.Dockerfile
    environment:
      NODE_ENV: 'dev'
      BABEL_ENV: 'dev'
    ports:
      - "8080:8080"
    # volumes:
    #   - "client-volume:/src/client/node_modules:rw"
    # command: "npm run start"
    container_name: client-container

# volumes:
#   client-volume:
#     driver_opts:
#       type: none
#       device: ${CAMAGRU_LOCAL_VOL}
#       o: bind